name: Redis CI

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  specs:
    services:
      redis:
        image: redislabs/redismod
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
        ports:
          - 6379:6379

    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 1.2.0
          - 1.3.0
          - 1.4.1
          - latest
        experimental:
          - false

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal_version}}
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
